FROM node:20 as build

WORKDIR /app 

RUN npm i -g npm

COPY package*.json ./

RUN npm ci --omit=dev

COPY . ./

RUN ls -la --recursive ./

FROM gcr.io/distroless/nodejs20-debian11

ARG BACKEND_ENDPOINT SENTRY_DSN
ENV BACKEND_ENDPOINT=$BACKEND_ENDPOINT SENTRY_DSN=$SENTRY_DSN

COPY --from=build /app /app

WORKDIR /app

CMD ["npm", "start"]



