# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build app and run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
    - uses: actions/checkout@v4
    - name: Use Server.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./package-lock.json"
    - name: Install dependencies
      #working-directory: ./server
      run: npm ci
    - name: Build project
      run: npm run build --if-present
      #working-directory: ./server
    - name: Run tests
      #working-directory: ./server
      run: npm test

  push_to_digital_ocean_registry:
      name: Push Docker image to Digital Ocean
      runs-on: ubuntu-latest
      needs: build_and_test
      
      steps:
        - name: Check out repo
          uses: actions/checkout@v4
        
        # Install doctl.
        - name: Install doctl on Image
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_TOKEN }}
  
        - name: Iniciar sesión en DigitalOcean Container Registry
          run: echo ${{ secrets.DIGITALOCEAN_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_TOKEN }} --password-stdin 
    
        - name: Build and push Docker image - DigitalOcean
          uses: docker/build-push-action@v5 # v5.0.0
          with:
            context: .
            file: ./Dockerfile.prod
            push: true
            tags: ${{ secrets.DIGITALOCEAN_REGISTRY }}/${{ secrets.DIGITALOCEAN_CONTAINER }}/${{ secrets.DIGITALOCEAN_REPO }}:latest
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              BACKEND_ENDPOINT=${{ secrets.BACKEND_ENDPOINT }}
              SENTRY_DSN=${{ secrets.SENTRY_DSN }}
